# Generated by Django 3.2.5 on 2021-11-26 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المصنع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة المصنع')),
                ('hour_price', models.IntegerField(blank=True, null=True, verbose_name='حساب الساعه')),
                ('machine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المكنة')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الموبيل')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضيف بواسطة')),
            ],
        ),
    ]
