# Generated by Django 3.2.5 on 2021-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='يعمل'),
        ),
    ]
