# Generated by Django 3.2.5 on 2021-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0004_factory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='تاريخ البداية'),
        ),
    ]
